baseURL: # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: charlola.mode
paginate: 5
theme: charlolamode



menu:
    main:
        - name: Contact
          url: /contact/
          weight: 30
        - name: Blog
          url: /blog/
          weight: 20

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Author's Name


    defaultTheme: dark
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Dracula Charlolamode Hugo Theme
        description: |

          I love the Dracula Theme, so here is my rendition of my favorite hugo theme.
           Long Live LAMP stacks
        

          This is a minimalistic theme template for websites, with a Dracula Theme spin to it.
        imageUrl: "/images/Flaticon_Dracula_597560.svg.png"
        imageTitle: The Count
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Official Dracula Theme
              url: https://draculatheme.com/
    mainSections:
      - blog

    socialIcons:
        - name: mastodon
          url: "https://mastodon.social/@Randoneering@fosstodon.org"
        - name: github
          url: "https://github.com/randoneering"
        - name: linkedin
          url: "https://www.linkedin.com/in/justin-frye-b4b14763/"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

